### ISSUE TITLE
贫富不均问题

### ISSUE THREAD

**Issue by yufree** [yufree/notes#12]
贫富不均篇

- [美国财富流动中的种族歧视可视化，很好的数据集，有时间考虑把其中华人的部分挑出来分析下](https://www.nytimes.com/interactive/2018/03/19/upshot/race-class-white-and-black-men.html)
- [美国财富分配的不平等](http://apps.urban.org/features/wealth-inequality-charts/)
- [美国中产现金流](https://www.wsj.com/articles/cash-crunch-for-many-is-a-monthly-woe-1432094467)
![](https://si.wsj.net/public/resources/images/NA-CF868_VOLATI_16U_20150519183912.jpg)
- [世界财富分配](http://www.pewglobal.org/interactives/global-population-by-income/)
- [OECD数据中财富的不平等](https://www.wsj.com/articles/oecd-sees-continued-rise-in-growth-harming-inequality-1432198801)
![](https://si.wsj.net/public/resources/images/EI-CN097_INEQUA_16U_20150521125107.jpg)
- [美国各专业毕业后薪水](https://blogs.wsj.com/economics/2015/02/19/a-new-degree-in-architecture-computers-or-health-is-worth-more-than-decades-of-job-experience/)
![](https://i1.wp.com/online.wsj.com/media/Majors.png)
- [穷人富人的开支](https://blogs.wsj.com/economics/2015/04/06/how-the-rich-and-poor-spend-and-earn-their-money/)
![image](https://user-images.githubusercontent.com/2356936/33814934-b9f30ec2-ddfb-11e7-953a-12d428176032.png)
- [美国贫穷问题](https://www.vox.com/2015/9/2/9248801/extreme-poverty-2-dollars)
- [欧洲人如何花钱](https://www.economist.com/blogs/graphicdetail/2015/09/daily-chart-12?fsrc=rss)
![](https://cdn.static-economist.com/sites/default/files/images/2015/09/blogs/graphic-detail/20150919_woc651_1.png)
- [美国各地房价中位数与年收入中位数比值分布，中位数1:3，大城市则普遍需要10年以上，这大概解释了部分留学生短期不回国的趋势，家庭事业起步期生存压力比国内小太多](https://nation.maps.arcgis.com/apps/Cascade/index.html)
- [美国34年收入增长率分布趋势，从共同富裕走向马太效应，中国差不多也应是这个趋势，本以为文章会讨论背后诸如资本流动、技术进步的原因，结果转头就开始黑川普取消医保了](https://www.nytimes.com/interactive/2017/08/07/opinion/leonhardt-income-inequality.html)
- [按美国的相对人均收入划分，60年有101个国家地区属于中等收入（有中国大陆），到08年只有13个国家地区进入高收入（没有中国大陆），这大概是最直观的中等收入陷阱 #经济学人#](https://www.economist.com/blogs/graphicdetail/2017/10/daily-chart-6)
- [最近几年讨论的全球尺度财富分配不均扩大化并不限于现代社会，考古学家计算了幼发拉底河流域文明到庞贝古城的基尼系数，发现这1000年来财富不平等是不断加剧的，农业文明的出现可能是背后推手，因为财富的积累在农业社会比游牧采集社会更容易发生](https://www.economist.com/blogs/graphicdetail/2017/11/daily-chart-17?fsrc=rss)
- [#华盛顿邮报 美国1980-2014年，收入前十万分之一的人财富增长616%，1%的人增长194%，底层20%的人只增长了4%，收入的幂律分布可能对新技术的高投入研发与提高市场活力有益，只是受益人可能也只是那前1%，民众通过票权重新洗牌的风险越来越高，所以…政府会不会大力发展文化产业来娱民转移对政治的注意力呢？](https://www.washingtonpost.com/news/wonk/wp/2017/12/15/u-s-lawmakers-are-redistributing-income-from-the-poor-to-the-rich-according-to-massive-new-study/?utm_term=.564de20f7bb6)
- [#经济学人 很多跨国公司想在印度重现中国的中产爆发潮，结果惨淡，财富在全球尺度内都在向精英超量累计，这个时代（也就起始于近两年）已经不容易造就中产了，大众购买力上不去很难谈发展](https://www.economist.com/news/briefing/21734382-multinational-businesses-relying-indian-consumers-face-disappointment-indias-missing-middle)
- [财富不平等的图](https://apps.urban.org/features/wealth-inequality-charts/)
- [美国不同收入人群的开支比例，差距最大的是房产开支，而且低收入者基本是入不敷出的](http://flowingdata.com/2018/02/08/how-different-income-groups-spend-money/)
![](https://i0.wp.com/flowingdata.com/wp-content/uploads/2018/02/spending_main_categories-desktop.png?zoom=2&w=1090)
- [贫穷的生理心理恶性循环](https://www.brookings.edu/blog/social-mobility-memos/2015/02/19/the-high-costs-of-being-poor-in-america-stress-pain-and-worry/)

- [美国职业性别变迁史，65年来更多女性进入劳动力市场，但职业倾向性还是比较明显，377个职业男女主导关系不变，82个职业发生反转，其中72个是男转女，有些职业男女比则一直在变化](http://flowingdata.com/2017/09/11/most-female-and-male-occupations-since-1950/)
- [11-16年美国各行各业转行大调查，我在环境、化学、生物、物理、药学科学家这些理科职业间发现了个奇妙的循环，此外其实科学家也有不少去修路、收银、保洁、开出租、厨子等职业，相比一入行就稳定的律师、会计师、医师还有教师，真正实现了“学好数理化，走遍天下都不怕”… ](http://flowingdata.com/2017/11/16/switching-jobs/)
- [美国各州职业变化](https://www.npr.org/sections/money/2015/02/05/382664837/map-the-most-common-job-in-every-state)
- [美国高校调研发现，虽然结婚门当户对还是主流，但出身不同的学生结婚模式有区别，富裕层通常结婚比较早且更追求门当户对，非富裕层则普遍结婚比较晚](https://www.nytimes.com/interactive/2018/03/29/upshot/college-marriage-class-differences.html)

**Comment by wishchin** [comment]
阿淼，博学不是坏事，但各方面知识吸收太多会分散精力的。
